---
title: "Descriptive_Statistics"
author: "Jake Lieberfarb"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = T, message = T)
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```



```{r Load 2015 data}
loadPkg('dplyr')
loadPkg('readxl')

#Read in general census data
census_2015 <- read.csv(file = 'acs2015updated.csv')

#Read in Specifically Education Data
edu_data_2015 <- read.csv("ACS_15_5YR_B15003_renamed.csv", skip = 1) %>% mutate(Id2 = as.numeric(Id2))

#Read in Freedom Data
freedom <- read_excel("Freedom_In_The_50_States_2018.xlsx", sheet = "Overall")

#Combine
census_edu_2015 <- left_join(census_2015, edu_data_2015, by = c("CensusTract" = "Id2"))
full_2015 <- full_join(census_edu_2015, freedom %>% filter(Year == 2015), by = "State") 

#For the education data, we will need to divide the count by the total
full_2015_eduProp <- full_2015 %>% mutate(PropHighSchool = EstHighSchool/EstTotal,
                                          PropBachelors = EstBachelors/EstTotal,
                                          PropDoctorate = EstDoctorate/EstTotal)
```

```{r Load 2017 data}
#Read in general census data
census_2017 <- read.csv(file = 'acs2017_census_tract_data.csv') %>% mutate(CensusTract = TractId, TractId = NULL) %>% left_join(census_2015 %>% select(INTPTLAT, INTPTLONG, GEOID, CensusTract), by = 'CensusTract')

#Read in Specifically Education Data
```


```{r Load 2017 data}



#New DF with 41 Columns
edu_data_2017 <- read.csv("ACS_17_5YR_B15003_renamed.csv", skip = 1) %>% mutate(Id2 = as.numeric(Id2))

#Read in Freedom Data
freedom <- read_excel("Freedom_In_The_50_States_2018.xlsx", sheet = "Overall")

#Combine
census_edu_2017 <- left_join(census_2017, edu_data_2017, by = c("CensusTract" = "Id2"))

full_2017 <- full_join(census_edu_2017, freedom %>% filter(Year == 2015), by = "State")

#For the education data, we will need to divide the count by the total
full_2017_eduProp <- full_2017 %>% mutate(PropHighSchool = EstHighSchool/EstTotal,
                                          PropBachelors = EstBachelors/EstTotal,
                                          PropDoctorate = EstDoctorate/EstTotal)

#Subsetting.DepVar -> income IndVar -> Work-related ones, and Freedom
full_2017IPC <- subset(full_2017, select = -c(VotingAgeCitizen, IncomePerCapErr, IncomeErr, Drive, Carpool, Transit, Walk, OtherTransp, MeanCommute, EstTotal) )
full_2017IPC <- subset(full_2017IPC, select = -c(33:83) )
full_2017IPC <- subset(full_2017IPC, select = -c(42:60) )
#full_2017IPC <- subset(full_2017IPC, select = c(42:60) )



#New DF with 41 Columns
str(full_2017IPC)


```




```{r Remove Outliers}

# Fix outliers
outlierKD2 <- function(df, var, rm=FALSE) { 
    #' Original outlierKD functino by By Klodian Dhana,
    #' https://www.r-bloggers.com/identify-describe-plot-and-remove-the-outliers-from-the-dataset/
    #' Modified to have third argument for removing outliers inwtead of interactive prompt, 
    #' and after removing outlier, original df will not be changed. The function returns the new df, 
    #' which can be saved as original df name if desired.
    #' Check outliers, and option to remove them, save as a new dataframe. 
    #' @param df The dataframe.
    #' @param var The variable in the dataframe to be checked for outliers
    #' @param rm Boolean. Whether to remove outliers or not.
    #' @return The dataframe with outliers replaced by NA if rm==TRUE, or df if nothing changed
    #' @examples
    #' outlierKD2(mydf, height, FALSE)
    #' mydf = outlierKD2(mydf, height, TRUE)
    #' mydfnew = outlierKD2(mydf, height, TRUE)
    dt = df # duplicate the dataframe for potential alteration
    var_name <- eval(substitute(var),eval(dt))
    na1 <- sum(is.na(var_name))
    m1 <- mean(var_name, na.rm = T)
    par(mfrow=c(2, 2), oma=c(0,0,3,0))
    boxplot(var_name, main="With outliers")
    hist(var_name, main="With outliers", xlab=NA, ylab=NA)
    outlier <- boxplot.stats(var_name)$out
    mo <- mean(outlier)
    var_name <- ifelse(var_name %in% outlier, NA, var_name)
    boxplot(var_name, main="Without outliers")
    hist(var_name, main="Without outliers", xlab=NA, ylab=NA)
    title("Outlier Check", outer=TRUE)
    na2 <- sum(is.na(var_name))
    cat("Outliers identified:", na2 - na1, "\n")
    cat("Propotion (%) of outliers:", round((na2 - na1) / sum(!is.na(var_name))*100, 1), "\n")
    cat("Mean of the outliers:", round(mo, 2), "\n")
    m2 <- mean(var_name, na.rm = T)
    cat("Mean without removing outliers:", round(m1, 2), "\n")
    cat("Mean if we remove outliers:", round(m2, 2), "\n")
    
    # response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ")
    # if(response == "y" | response == "yes"){
    if(rm){
        dt[as.character(substitute(var))] <- invisible(var_name)
        #assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
        cat("Outliers successfully removed", "\n")
        return(invisible(dt))
    } else {
        cat("Nothing changed", "\n")
        return(invisible(df))
    }
}

```

```{r income}
loadPkg("ggplot2")

# NA's
#full_2017IPC<-full_2017IPC[!is.na(IncomePerCap)]
sum(is.na(full_2017IPC$IncomePerCap))

#removed outliers 
full_2017IPC <- outlierKD2(full_2017IPC, IncomePerCap, TRUE)
#Length
length(full_2017IPC$IncomePerCap)


#Histogram of dependent variable
hist(full_2017IPC$IncomePerCap, 
        col = "#a8c2fb",
        main = "Income per Capita",
        xlab = "US Dollars")

#ggplot
qqnorm(full_2017IPC$IncomePerCap, main="Q-Q plot of IncomePerCap")
qqline(full_2017IPC$IncomePerCap)

#Mean after removing NA's
format(mean(full_2017IPC$IncomePerCap, na.rm = TRUE))

#Summary after removing NA's
summary(full_2017IPC$IncomePerCap)
#standard deviation
sd(full_2017IPC$IncomePerCap, na.rm = TRUE)

#normality test 
#shapiro.test(full_2017IPC$IncomePerCap)
#ks.test(full_2017IPC$IncomePerCap)
```



```{r variables}


#Freedom Scores 
#OverallFreedom
#RegulatoryPolicy
#FiscalPolicy

#Work Variations 

#Professional
#Production
#Unemployment
#Office
#Service 
#Construction

#Ethnic Variation
#Black
#Hispanic
#Asian
#White
#Native

```

```{r Freedom scores}
loadPkg("dvmisc")
#Group by Economic Freedom
GroupEF <- quant_groups(full_2017IPC$EconomicFreedom, 4)
str(GroupEF)
#Boxplot of IncomePerCap by Economic Freedom
plot(IncomePerCap ~ GroupEF, data=full_2017IPC, main="IncomePerCap and GroupEF", col=c("#ffd18b","#ffb76d","#ffa264", "#ff875f") )
summary(full_2017IPC$EconomicFreedom)

#Histogram of Economic Freedom
hist(full_2017IPC$EconomicFreedom, 
        col = "#ffd18b",
        main = "Economic Freedom")

#qqplot of Econoimc Freedom
qqnorm(full_2017IPC$EconomicFreedom, main="Q-Q plot of Economic Freedom")
qqline(full_2017IPC$EconomicFreedom)


#Group by PersonalFreedom
GroupPF <- quant_groups(full_2017IPC$PersonalFreedom, 4)
str(GroupPF)
#Boxplot of IncomePerCap by Personal Freedom
plot(IncomePerCap ~ GroupPF, data=full_2017IPC, main="IncomePerCap and GroupPF", col=c("#BFBFFF","#A3A3FF", "#7879FF", "#4949FF") )
summary(full_2017IPC$PersonalFreedom)

#Histogram of Economic Freedom
hist(full_2017IPC$PersonalFreedom, 
        col = "#A3A3FF",
        main = "Personal Freedom")

#qqplot of Econoimc Freedom
qqnorm(full_2017IPC$PersonalFreedom, main="Q-Q plot of Personal Freedom")
qqline(full_2017IPC$PersonalFreedom)

#Group by Regulatory Policy
GroupRP <- quant_groups(full_2017IPC$RegulatoryPolicy, 4)
str(GroupRP)
#Boxplot of IncomePerCap by Regulatory Policy
plot(IncomePerCap ~ GroupRP, data=full_2017IPC, main="IncomePerCap and GroupRP", col=c("#FFDF01","#FED901", "#FFCF00", "#FEC300") )
summary(full_2017IPC$RegulatoryPolicy)

#Histogram of Regulatory Policy
hist(full_2017IPC$RegulatoryPolicy, 
        col = "#A3A3FF",
        main = "Regulatory Policy ")

#qqplot of Regulatory Policy
qqnorm(full_2017IPC$RegulatoryPolicy, main="Q-Q plot of Regulatory Policy")
qqline(full_2017IPC$RegulatoryPolicy)


#Group by Fiscal Policy
GroupFP <- quant_groups(full_2017IPC$FiscalPolicy, 4)
str(GroupFP)
#Boxplot of IncomePerCap by Fiscal Policy
plot(IncomePerCap ~ GroupFP, data=full_2017IPC, main="IncomePerCap and GroupFP", col=c("#7EFFD4","#70EBBA", "#64D8A7", "#58BD95") )
summary(full_2017IPC$FiscalPolicy)

#Histogram of Economic Freedom
hist(full_2017IPC$FiscalPolicy, 
        col = "#A3A3FF",
        main = "Fiscal Policy")

#qqplot of Econoimc Freedom
qqnorm(full_2017IPC$FiscalPolicy, main="Q-Q plot of Fiscal Policy")
qqline(full_2017IPC$FiscalPolicy)

#Group by Overall Freedom
GroupOF <- quant_groups(full_2017IPC$OverallFreedom, 4)
str(GroupOF)
#Boxplot of IncomePerCap by Overall Freedom
plot(IncomePerCap ~ GroupOF, data=full_2017IPC, main="IncomePerCap and GroupOF", col=c("#C0C6CB","#98A5C0", "#7688BB", "#536CB5") )
summary(full_2017IPC$OverallFreedom)

#Histogram of Overall Freedom
hist(full_2017IPC$PersonalFreedom, 
        col = "#A3A3FF",
        main = "Overall Freedom")

#qqplot of Overall Freedom
qqnorm(full_2017IPC$PersonalFreedom, main="Q-Q plot of Overall Freedom")
qqline(full_2017IPC$PersonalFreedom)
```

```{r Work variations}
#Group by Unemployment
GroupUnemployment <- quant_groups(full_2017IPC$Unemployment, 4)
str(GroupUnemployment)
#Boxplot of IncomePerCap by Unemployment
plot(IncomePerCap ~ GroupUnemployment, data=full_2017IPC, main="IncomePerCap and GroupUnemployment", col=c("#FFF57B","#FFE469", "#FECC51", "#FCB033") )
summary(full_2017IPC$Unemployment)

#Histogram of Unemployment
hist(full_2017IPC$Unemployment, 
        col = "#A3A3FF",
        main = "Unemployment")

#qqplot of Unemployment Unemployment
qqnorm(full_2017IPC$Unemployment, main="Q-Q plot of Unemployment")
qqline(full_2017IPC$Unemployment)

#Group by Professional
GroupProfessional <- quant_groups(full_2017IPC$Professional, 4)
str(GroupProfessional)
#Boxplot of IncomePerCap by Professional
plot(IncomePerCap ~ GroupProfessional, data=full_2017IPC, main="IncomePerCap and GroupProfessional", col=c("#F3D8F2","#E6B2E4", "#D88DD5", "#CA68C7") )
summary(full_2017IPC$Professional)

#Histogram of Professional
hist(full_2017IPC$PersonalFreedom, 
        col = "#D88DD5",
        main = "Professional")

#qqplot of Professional
qqnorm(full_2017IPC$Professional, main="Q-Q plot of Professional")
qqline(full_2017IPC$Professional)


#Group by Office
GroupOffice <- quant_groups(full_2017IPC$Office, 4)
str(GroupOffice)
#Boxplot of IncomePerCap by Office
plot(IncomePerCap ~ GroupOffice, data=full_2017IPC, main="IncomePerCap and GroupOffice", col=c("#D1FFD5","#B4FFB2", "#98FF98", "#79F58A") )
summary(full_2017IPC$Office)
#Histogram of Professional
hist(full_2017IPC$Office, 
        col = "#FECC51",
        main = "Office")

#qqplot of Professional
qqnorm(full_2017IPC$Professional, main="Q-Q plot of Professional")
qqline(full_2017IPC$Professional)


#Group by Service
GroupService <- quant_groups(full_2017IPC$Service, 4)
str(GroupService)
#Boxplot of IncomePerCap by Service
plot(IncomePerCap ~ GroupService, data=full_2017IPC, main="IncomePerCap and GroupService", col=c("#E0BCBF","#D8ABB1", "#CF989F", "#C0838C") )
summary(full_2017IPC$Service)

#Histogram of Service
hist(full_2017IPC$Service, 
        col = "#79F58A",
        main = "Service")

#qqplot of Service
qqnorm(full_2017IPC$Service, main="Q-Q plot of Service")
qqline(full_2017IPC$Service)

#Group by Construction
GroupConstruction <- quant_groups(full_2017IPC$Construction, 4)
str(GroupConstruction)
#Boxplot of IncomePerCap by Construction
plot(IncomePerCap ~ GroupConstruction, data=full_2017IPC, main="IncomePerCap and GroupConstruction", col=c("#A9AB98","#949180", "#7D7968", "#5E594F") )
summary(full_2017IPC$Construction)
#Histogram of Construciton
hist(full_2017IPC$Construction, 
        col = "#C0838C",
        main = "Construction")

#qqplot of Construction
qqnorm(full_2017IPC$Construction, main="Q-Q plot of Construction")
qqline(full_2017IPC$Construction)

#Group by Production
GroupProduction <- quant_groups(full_2017IPC$Production, 4)
str(GroupProduction)
#Boxplot of IncomePerCap by Production
plot(IncomePerCap ~ GroupProduction, data=full_2017IPC, main="IncomePerCap and Production", col=c("#F3D8F2","#E6B2E4", "#D88DD5", "#CA68C7") )
summary(full_2017IPC$Production)
#Histogram of Producrtion
hist(full_2017IPC$Production, 
        col = "#E6B2E4",
        main = "Production")

#qqplot of Professional
qqnorm(full_2017IPC$Production, main="Q-Q plot of Production")
qqline(full_2017IPC$Production)
```

```{r  Ethnic Variatons}
loadPkg("dvmisc")
#Group by Black
GroupBlack <- quant_groups(full_2017IPC$Black, 4)
str(GroupBlack)
#Boxplot of IncomePerCap by Black Population
plot(IncomePerCap ~ GroupBlack, data=full_2017IPC, main="IncomePerCap and GroupBlack", col=c("#d0dfff","#a8c2fb", "#86abf9", "#6893ee") )
summary(full_2017IPC$Black)

#Histogram of Black
hist(full_2017IPC$Black, 
        col = "#d0dfff",
        main = "Black")

#qqplot of Black
qqnorm(full_2017IPC$Black, main="Q-Q plot of Black")
qqline(full_2017IPC$Black)

#Group by Hispanic
GroupHispanic <- quant_groups(full_2017IPC$Hispanic, 4)
str(GroupHispanic)
#Boxplot of IncomePerCap by Hispanic Population
plot(IncomePerCap ~ GroupHispanic, data=full_2017IPC, main="IncomePerCap and GroupHispanic", col=c("#F6BDC0","#F1959B", "#F07470", "#EA4C46") )
summary(full_2017IPC$Hispanic)
#Histogram of Hispanic
hist(full_2017IPC$Hispanic, 
        col = "#EA4C46",
        main = "Hispanic")

#qqplot of Hispanic
qqnorm(full_2017IPC$Hispanic, main="Q-Q plot of Production")
qqline(full_2017IPC$Hispanic)

#Group by Asians
GroupAsian <- quant_groups(full_2017IPC$Asian, 3)
str(GroupAsian)
#Boxplot of IncomePerCap by Asian Population
plot(IncomePerCap ~ GroupAsian, data=full_2017IPC, main="IncomePerCap and GroupAsian", col=c("#FFE6C8","#FFCCBE", "#EFABA0", "#D6806F") )
summary(full_2017IPC$Asian)
#Histogram of Asian
hist(full_2017IPC$Asian, 
        col = "#FFE6C8",
        main = "Asian")

#qqplot of Asian
qqnorm(full_2017IPC$Asian, main="Q-Q plot of Asian")
qqline(full_2017IPC$Asian)

#Group by White
GroupWhite <- quant_groups(full_2017IPC$White, 4)
str(GroupWhite)
#Boxplot of IncomePerCap by White Population
plot(IncomePerCap ~ GroupWhite, data=full_2017IPC, main="IncomePerCap and GroupWhite", col=c("#B5651D", "#A4550A", "#964B00", "#834200") )
summary(full_2017IPC$White)
#Histogram of White
hist(full_2017IPC$White, 
        col = "#964B00",
        main = "White")

#qqplot of White
qqnorm(full_2017IPC$White, main="Q-Q plot of Production")
qqline(full_2017IPC$White)



```

```{r geo scatter}
full_2015_2 <- subset(full_2015, INTPTLONG > -150 & INTPTLONG < -50 & INTPTLAT > 24 & INTPTLAT < 50) 
full_2017_2 <- subset(full_2017, INTPTLONG > -150 & INTPTLONG < -50 & INTPTLAT > 24 & INTPTLAT < 50) 

#Hispanic 
loadPkg("ggplot2")
ggplot(full_2015_2, aes( x= INTPTLONG, y = INTPTLAT, color = Hispanic)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2015",
        x=" Latitude",
        y = "Longitude")

ggplot(full_2017_2, aes( x= INTPTLONG, y = INTPTLAT, color = Hispanic)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2017",
        x=" Latitude",
        y = "Longitude")
#Native 
ggplot(full_2015_2, aes( x= INTPTLONG, y = INTPTLAT, color = Native)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2015",
        x=" Latitude",
        y = "Longitude")

ggplot(full_2017_2, aes( x= INTPTLONG, y = INTPTLAT, color = Native)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2017",
        x=" Latitude",
        y = "Longitude")
#White 
ggplot(full_2015_2, aes( x= INTPTLONG, y = INTPTLAT, color = White)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2015",
        x=" Latitude",
        y = "Longitude")

ggplot(full_2017_2, aes( x= INTPTLONG, y = INTPTLAT, color = White)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2017",
        x=" Latitude",
        y = "Longitude")
#Black
ggplot(full_2015_2, aes( x= INTPTLONG, y = INTPTLAT, color = Black)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2015",
        x=" Latitude",
        y = "Longitude")

ggplot(full_2017_2, aes( x= INTPTLONG, y = INTPTLAT, color = Black)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2017",
        x=" Latitude",
        y = "Longitude")
#Asian
ggplot(full_2015_2, aes( x= INTPTLONG, y = INTPTLAT, color = Asian)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2015",
        x=" Latitude",
        y = "Longitude")

ggplot(full_2017_2, aes( x= INTPTLONG, y = INTPTLAT, color = Asian)) + 
  geom_point(size=0.005) + scale_color_gradient(low="orange", high="red") +
  labs (title="Scatter Plot: Spanish Ethnicity in 2017",
        x=" Latitude",
        y = "Longitude")
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
